markdown: kramdown
title: Zagaja.com
paginate: 5
paginate_path: /page/:num
permalink: /:year/:month/:title/
description: "Matt Zagaja's personal blog. Musings on politics, technology, and other geeky things."
url: https://www.zagaja.com
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
author:
  twitter: mzagaja
defaults:
  -
    scope:
      path: "page"
    values:
      sitemap: false
