markdown: kramdown
title: Zagaja.com
description: "Matt Zagaja's personal blog. Musings on politics, technology, and other geeky things."
url: https://www.zagaja.com
incremental: true
permalink: /:year/:month/:title/
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
author:
  twitter: mzagaja
defaults:
  -
    scope:
      path: "page"
    values:
      sitemap: false
algolia:
  application_id: ADZBG2997L
  index_name: jekyll
  search_only_api_key: b8c639bf58a56694e5b07d3b68d685b1
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: /page/:num/
  limit: 0
  sort_reverse: true
