markdown: rdiscount
rdiscount:
  extensions: [ footnotes ]
name: Matt Zagaja
highlighter: true
paginate: 5
permalink: /:year/:month/:title/
description: "Matt Zagaja's personal blog. Musings on politics, technology, and other geeky things."
url: http://www.zagaja.com
sitemap:
  include_posts: 
    - "/index.html"